name: flutter_splash
description: Easily create simple splash screen for flutter applications
version: 1.0.0
author: Nor Gelera <chrome.nor@gmail.com>
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
